package com.kurento.commons.sip.agent;

public enum TypeStun {
	ERROR_STUN, BLOCKED_UDP, SYMMETRIC_UDP_FIREWALL, FULL_CONE, OPEN_ACCESS, PORT_RESTRICTED_CONE, RESTRICTED_CONE, SYMMETRIC_CONE, UNKNOW
}
